### GET - get all
GET http://localhost:3000/api/images HTTP/1.1

### GET - get by id
GET http://localhost:3000/api/images/1681894404250 HTTP/1.1

### DELETE - delete by id
DELETE http://localhost:3000/api/images/1681894404250 HTTP/1.1

### PATCH - update by id
PATCH  http://localhost:3000/api/images HTTP/1.1
content-type: application/json

{
  "id": "1683468468625",
  "change": "change"
}

### POST - send file
POST http://localhost:3000/api/images HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY4NDEzMzk0MDgxMSwiZW1haWwiOiJncnplZ29yenN6ZXdjenlrQGdtYWlsLmNvbSIsImlhdCI6MTY4NDEzMzk0MywiZXhwIjoxNjg0MjIwMzQzfQ.LUwV7dbWpJWUoJzJrFuszMAeNBg66pYt9qvT3B66wOM

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="testInput.jpg"
Content-Type: image/jpeg

< ./testInput.jpg 

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

myAlbum
------FormBoundary1234