### GET - get file by id 
GET http://localhost:3000/api/getfile/1685112995829 HTTP/1.1

### GET - get file from path
GET http://localhost:3000/api/uploads/1685112984129/1685112995829.jpg HTTP/1.1

### GET - get image metadata by id
GET http://localhost:3000/api/filters/metadata/1681895692255 HTTP/1.1

### PATCH - update by id
PATCH  http://localhost:3000/api/filters HTTP/1.1
content-type: application/json

{
    "id": "1682354807509",
    "operation": "crop",
    // crop
    // tint
    // resize
    // rotate
    // grayscale
    // negate

    "tint": {
        "r": 255,
        "g": 0,
        "b": 0
    },
    "crop": {
        "width": 100,
        "height": 200,
        "left": 20,
        "top": 20
    },
    "resize": {
        "width": 100,
        "height": 100
    },
    "rotate": 90
}