### POST - send new post
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY4NjUxNDE0MDg2NSwiZW1haWwiOiJncnplZ29yenN6ZXdjenlrQGdtYWlsLmNvbSIsImlhdCI6MTY4NjUxNDE0MSwiZXhwIjoxNjg2NjAwNTQxfQ.YThccY5b5bxJ_5Uem5-ti9FGbn_yEQW_Vb1sLQRGLyk

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="testInput.jpg"
Content-Type: image/jpeg

< ./testInput.jpg 

------FormBoundary1234
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
    "description": "What a beautiful place :)",
    "location": "Madrit",
    "tags": ["insta", "food", "travel"],
    "date": ""
}
------FormBoundary1234

### GET - get all 
GET http://localhost:3000/api/posts HTTP/1.1

### GET - get by id
GET http://localhost:3000/api/posts/1685341684559 HTTP/1.1

### DELETE - delete by id
DELETE http://localhost:3000/api/posts/1684771834317 HTTP/1.1

### PATCH - update post
PATCH http://localhost:3000/api/posts HTTP/1.1
Content-Type: "application/json"
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY4NjUxNDE0MDg2NSwiZW1haWwiOiJncnplZ29yenN6ZXdjenlrQGdtYWlsLmNvbSIsImlhdCI6MTY4NjUxNDE0MSwiZXhwIjoxNjg2NjAwNTQxfQ.YThccY5b5bxJ_5Uem5-ti9FGbn_yEQW_Vb1sLQRGLyk

{
    "id": 1686514154865,
    "description": "First time here!",
    "location": "Rome",
    "tags": ["sculptures", "architecture", "travel"]
}